services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper1
    ports:
      - 2182:2181
  
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka1
    ports:
      - 9093:9093
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181